// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package db

import (
	"github.com/lmx-Hexagram/gemini-generator/internal/service/config"
)

// Injectors from wire.go:

func InitDep() *service {
	v := provideDbMap()
	dbMap := config.ProvideDbMap()
	service2 := &service{
		DbMap:       v,
		DbConfigMap: dbMap,
	}
	return service2
}
